CREATE TABLE band (bandName varchar(50) primary key, creation YEAR, genre varchar(50));
INSERT INTO band VALUES ('Crazy Duo',2015 ,'rock'),('Luna',2009,'classical'),('Mysterio',2019,'pop');
ALTER TABLE singer RENAME TO musician;
ALTER TABLE musician CHANGE COLUMN singerName musicianName varchar(50);
ALTER TABLE musician ADD COLUMN role varchar(50);
ALTER TABLE musician ADD COLUMN bandName varchar(50);
ALTER TABLE musician ADD CONSTRAINT FOREIGN KEY (bandName) REFERENCES band(bandName);
UPDATE musician set role='vocals' WHERE musicianName='Alina';
UPDATE musician set role='guitar' WHERE musicianName='Mysterio';
UPDATE musician set role='percussion' WHERE musicianName='Rainbow';
UPDATE musician set role='piano' WHERE musicianName='Luna';
UPDATE musician set bandName='Crazy Duo' WHERE musicianName='Alina' or musicianName='Rainbow';
UPDATE musician set bandName='Mysterio' WHERE musicianName='Mysterio';
UPDATE musician set bandName='Luna' WHERE musicianName='Luna';